defaultBaseImage: gcr.io/distroless/static-debian11:latest
builds:
- env:
  - CGO_ENABLED=0
  dir: cmd/external-dns
  main: .
  flags:
  - -v
  - -tags
  - "{{.Env.BUILD_TAGS}}"
  ldflags:
  - -s
  - -w
  - -X sigs.k8s.io/external-dns/pkg/apis/externaldns.Version={{.Env.VERSION}}

